### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by athompso** [akpoff/spf_fetch#1]
Looks you can extend the IPv4 regex to include IPv6.  Not terribly clean, but possible.

Ways to do it in Bourne shell:
* https://gist.github.com/anonymous/0b04a03da268723be3d821eb4f7cfd4b
* https://twobit.us/2011/07/validating-ip-addresses/
* https://stackoverflow.com/questions/14697403/expand-ipv6-address-in-shell-script
* https://github.com/mutax/IPv6-Address-checks/blob/master/bash/v6test.sh

**Comment by akpoff** [comment]
Found a better way to address this.

Still using dig to get the ips. Added -t [filter] feature to allow filtering, processing or transforming ip addresses before writing. filters/filter_sipcalc uses sip_calc to verify addresses and CIDR blocks.
